"""Import job metadata used by the API, health checks and admin views."""

IMPORT_JOB_DEFINITIONS = {
    "hc3_light_5min": {
        "title": "Lys / lux fra HC3",
        "category": "Lys",
        "source": "HC3",
        "expected_interval_minutes": 7,
        "warning_after_minutes": 15,
        "description": "5-minutters luxlogg og status for utelys.",
    },
    "hc3_ventilation_5min": {
        "title": "Ventilasjon / temperatur fra HC3",
        "category": "Ventilasjon",
        "source": "HC3",
        "expected_interval_minutes": 7,
        "warning_after_minutes": 15,
        "description": "5-minutters temperatur, effekt og viftestatus.",
    },
    "yr_weather_refresh": {
        "title": "Yr API",
        "category": "Vær",
        "source": "MET/Yr",
        "expected_interval_minutes": 70,
        "warning_after_minutes": 130,
        "description": "Værvarsel hentet fra Yr/MET når forrige varsel går ut.",
    },
    "hc3_energy_1min": {
        "title": "Energi fra HC3",
        "category": "Energi",
        "source": "HC3",
        "expected_interval_minutes": 2,
        "warning_after_minutes": 5,
        "description": "30-sekunders logging av realtime effekt og akkumulert kWh fra Fibaro.",
    },
    "roborock_sync": {
        "title": "Roborock logger",
        "category": "Renhold",
        "source": "QNAP",
        "expected_interval_minutes": 10,
        "warning_after_minutes": 30,
        "description": "Robotstatus, planlagte jobber og siste lokale/cloud-data.",
    },
    "owntracks_mqtt": {
        "title": "OwnTracks MQTT",
        "category": "Mobil",
        "source": "Mosquitto",
        "expected_interval_minutes": 30,
        "warning_after_minutes": 120,
        "description": "Siste posisjonsmelding fra OwnTracks via intern MQTT-broker.",
    },
    "sun2_daily_download": {
        "title": "Sun2 dagsfil nedlasting",
        "category": "Soling",
        "source": "QNAP",
        "expected_interval_minutes": 36 * 60,
        "warning_after_minutes": 72 * 60,
        "description": "Nattlig nedlasting av SUN2 dagsfil for import.",
    },
    "sun2_room_daily_import": {
        "title": "Sun2 dagsimport rom",
        "category": "Soling",
        "source": "QNAP",
        "expected_interval_minutes": 36 * 60,
        "warning_after_minutes": 72 * 60,
        "description": "Daglige summer per rom fra Sun2.",
    },
    "sun2_sessions_import": {
        "title": "Sun2 enkelttimer",
        "category": "Soling",
        "source": "QNAP",
        "expected_interval_minutes": 7,
        "warning_after_minutes": 20,
        "description": "Import av enkeltsolinger fra Sun2.",
    },
    "sun2_beds_import": {
        "title": "Sun2 senger",
        "category": "Soling",
        "source": "QNAP",
        "expected_interval_minutes": 7 * 24 * 60,
        "warning_after_minutes": 14 * 24 * 60,
        "description": "Seng-/rommetadata fra Sun2.",
    },
    "sun2_members_import": {
        "title": "Sun2 medlemmer",
        "category": "Soling",
        "source": "QNAP",
        "expected_interval_minutes": 7 * 24 * 60,
        "warning_after_minutes": 14 * 24 * 60,
        "description": "Medlemsregister og profilfelter fra Sun2.",
    },
    "sun2_product_sales_daily_import": {
        "title": "Sun2 produktsalg daglig",
        "category": "Soling",
        "source": "QNAP",
        "expected_interval_minutes": 36 * 60,
        "warning_after_minutes": 72 * 60,
        "description": "Daglig import av produktsalg fra Sun2 for dagsfordeling.",
    },
    "sun2_product_sales_monthly_import": {
        "title": "Sun2 produktsalg maanedskontroll",
        "category": "Soling",
        "source": "QNAP",
        "expected_interval_minutes": 40 * 24 * 60,
        "warning_after_minutes": 55 * 24 * 60,
        "description": "Maanedlig import av hele forrige maaned fra Sun2 for kontroll mot solingsoppgjor.",
    },
    "sun2_finance_settlement_monthly_import": {
        "title": "Sun2 finansoppgjor",
        "category": "Soling",
        "source": "QNAP",
        "expected_interval_minutes": 40 * 24 * 60,
        "warning_after_minutes": 55 * 24 * 60,
        "description": "Maanedlig import av Sun2 finanshistorikk for solomsetning og uregistrerte solinger.",
    },
    "elvia_monthly_import": {
        "title": "Elvia månedsfil",
        "category": "Energi",
        "source": "Manuell opplasting",
        "expected_interval_minutes": 40 * 24 * 60,
        "warning_after_minutes": 55 * 24 * 60,
        "description": "Månedlig import av strømforbruk fra Elvia.",
    },
    "easypark_parking_import": {
        "title": "EasyPark import",
        "category": "Parkering",
        "source": "EasyPark",
        "expected_interval_minutes": 26 * 60,
        "warning_after_minutes": 50 * 60,
        "description": "Automatisk nedlasting og import av parkeringsliste fra EasyPark.",
    },
    "parking_history_import": {
        "title": "Parkering historikk",
        "category": "Parkering",
        "source": "QNAP appdb",
        "expected_interval_minutes": None,
        "warning_after_minutes": None,
        "description": "Migrert EasyPark-historikk med kjoretoydata fra Statens vegvesen.",
    },
    "parking_vehicle_svv_sync": {
        "title": "Kjøretøydata fra SVV",
        "category": "Parkering",
        "source": "Statens vegvesen",
        "expected_interval_minutes": 30,
        "warning_after_minutes": 90,
        "description": "Løpende berikelse av registreringsnummer som mangler tekniske kjøretøydata.",
    },
    "parking_vehicle_biluppgifter_sync": {
        "title": "Biluppgifter Sverige",
        "category": "Parkering",
        "source": "Biluppgifter.se",
        "expected_interval_minutes": None,
        "warning_after_minutes": None,
        "description": "Oppslag av svenske registreringsnummer der SVV ikke fant kjoretoydata.",
    },
    "parking_vehicle_tjekbil_sync": {
        "title": "Tjekbil Danmark",
        "category": "Parkering",
        "source": "Tjekbil.dk",
        "expected_interval_minutes": None,
        "warning_after_minutes": None,
        "description": "Oppslag av danske registreringsnummer der SVV ikke fant kjoretoydata.",
    },
}

IMPORT_JOB_NUMBER_BY_NAME = {
    job_name: index + 1
    for index, job_name in enumerate(IMPORT_JOB_DEFINITIONS)
}
