"""Static system inventory for Fibaro10.

The inventory is deliberately code-owned so the admin UI, documentation and
tests can point to the same definition of which local apps are part of the
solution.
"""

from __future__ import annotations

from collections import Counter
from typing import Any


SYSTEM_COMPONENTS: list[dict[str, Any]] = [
    {
        "component": "fibaro10",
        "area": "Kjerne",
        "role": "FastAPI backend, V2 API, database, importstatus og adminflater",
        "runtime": "Docker",
        "compose_service": "fibaro10",
        "interface": "V2 web/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8110/",
        "health_url": "http://192.168.20.218:8110/health?details=true",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Kritisk",
        "has_web_interface": True,
    },
    {
        "component": "desktop_v2",
        "area": "Frontend",
        "role": "Samlet React/Ant Design reserveflate og funksjonsreferanse",
        "runtime": "Vite build levert av fibaro10",
        "compose_service": "fibaro10",
        "interface": "Reservegrensesnitt",
        "web_url": "",
        "local_url": "http://192.168.20.218:8110/",
        "health_url": "http://192.168.20.218:8110/health",
        "health": "/",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "lilletorget_mantis",
        "area": "Frontend",
        "role": "Gjeldende brukerflate med elleve Mantis-apper under én HTTPS-origin",
        "runtime": "Docker / Nginx",
        "compose_service": "lilletorget_mantis",
        "interface": "Mantis web/PWA",
        "web_url": "https://ny.lilletorget.net/",
        "local_url": "http://192.168.20.218:8170/",
        "health_url": "http://192.168.20.218:8170/ready",
        "health": "/ready",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "shell_app",
        "area": "Plattform",
        "role": "Forrige appvelger og reserveinngang til fagadapterne",
        "runtime": "Docker",
        "compose_service": "shell_app",
        "interface": "Reserve-appskall",
        "web_url": "",
        "local_url": "http://192.168.20.218:8150/",
        "health_url": "http://192.168.20.218:8150/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "revenue_app",
        "area": "Økonomi",
        "role": "Fagapplikasjon for omsetningsdashboard, utvikling og periodesammenligning",
        "runtime": "Docker",
        "compose_service": "revenue_app",
        "interface": "Separat intern webapp",
        "web_url": "",
        "local_url": "http://192.168.20.218:8151/",
        "health_url": "http://192.168.20.218:8151/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "parking_app",
        "area": "Parkering",
        "role": "Parkeringer, kjøretøy, oppgjør, områder, tidsanalyse og prognoser",
        "runtime": "Docker",
        "compose_service": "parking_app",
        "interface": "Separat intern webapp",
        "web_url": "",
        "local_url": "http://192.168.20.218:8152/",
        "health_url": "http://192.168.20.218:8152/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "sun_app",
        "area": "Soling",
        "role": "Soltimer, dagslinje, bilder, produkter, medlemmer, oppgjør og analyse",
        "runtime": "Docker",
        "compose_service": "sun_app",
        "interface": "Separat intern webapp",
        "web_url": "",
        "local_url": "http://192.168.20.218:8153/",
        "health_url": "http://192.168.20.218:8153/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "energy_app",
        "area": "Energi",
        "role": "Sanntidsforbruk, Elvia-kontroll, kurs/last og energibruk per solseng",
        "runtime": "Docker",
        "compose_service": "energy_app",
        "interface": "Separat intern webapp",
        "web_url": "",
        "local_url": "http://192.168.20.218:8154/",
        "health_url": "http://192.168.20.218:8154/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "operations_app",
        "area": "Bygg og drift",
        "role": "Ventilasjon, lys, dører, solrom, pullerter og robotrenhold",
        "runtime": "Docker",
        "compose_service": "operations_app",
        "interface": "Separat intern webapp",
        "web_url": "",
        "local_url": "http://192.168.20.218:8155/",
        "health_url": "http://192.168.20.218:8155/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "maintenance_app",
        "area": "Vedlikehold",
        "role": "Intern arbeidsflate for besøk, oppgaver, redigering og historikk",
        "runtime": "Docker",
        "compose_service": "maintenance_app",
        "interface": "Separat intern webapp",
        "web_url": "",
        "local_url": "http://192.168.20.218:8156/",
        "health_url": "http://192.168.20.218:8156/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "system_app",
        "area": "System",
        "role": "Datakilder, brukere, buildlogg, manual, varslinger og systemkontroll",
        "runtime": "Docker",
        "compose_service": "system_app",
        "interface": "Separat intern webapp",
        "web_url": "",
        "local_url": "http://192.168.20.218:8157/",
        "health_url": "http://192.168.20.218:8157/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "link_app",
        "area": "Kobling",
        "role": "Kandidater, Sun2-kontroll og treffgrunnlag for kobling mellom bil og Sun2-ID",
        "runtime": "Docker",
        "compose_service": "link_app",
        "interface": "Separat intern webapp",
        "web_url": "",
        "local_url": "http://192.168.20.218:8158/",
        "health_url": "http://192.168.20.218:8158/health",
        "health": "/health og /ready",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "online_dashboard",
        "area": "Mobil/ekstern",
        "role": "Eksternt dashboard med begrensede nøkkeltall",
        "runtime": "Docker",
        "compose_service": "online_dashboard",
        "interface": "Offentlig web",
        "web_url": "https://online.lilletorget.net/",
        "local_url": "",
        "health_url": "https://online.lilletorget.net/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "maintenance_mobile",
        "area": "Vedlikehold",
        "role": "Mobilapp for rask registrering av vedlikehold og oppgaver",
        "runtime": "Docker",
        "compose_service": "maintenance_mobile",
        "interface": "Offentlig web",
        "web_url": "https://vedl.lilletorget.net/",
        "local_url": "http://192.168.20.218:8112/",
        "health_url": "https://vedl.lilletorget.net/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "alarm_mobile",
        "area": "Alarm",
        "role": "Mobil alarmflate for dører, solrom, pullerter og trapp med dyplenker fra ntfy",
        "runtime": "Docker",
        "compose_service": "alarm_mobile",
        "interface": "Offentlig web",
        "web_url": "https://alarm.lilletorget.net/",
        "local_url": "http://192.168.20.218:8114/",
        "health_url": "http://192.168.20.218:8114/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "fibaro10ipad",
        "area": "Frontend",
        "role": "Separat iPad-grensesnitt for sentrale driftsbilder fra Fibaro10",
        "runtime": "Docker",
        "compose_service": "fibaro10ipad",
        "interface": "Offentlig web",
        "web_url": "https://ipad.lilletorget.net/",
        "local_url": "http://192.168.20.218:8113/",
        "health_url": "https://ipad.lilletorget.net/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "owntracks_service",
        "area": "Lokasjon",
        "role": "Separat FastAPI-tjeneste på owntracks.lilletorget.net for OwnTracks HTTP-inntak, lagring, waypoints og sonebesøk",
        "runtime": "Docker",
        "compose_service": "owntracks_service",
        "interface": "Offentlig web/API",
        "web_url": "https://owntracks.lilletorget.net/",
        "local_url": "http://192.168.20.218:8128/",
        "health_url": "https://owntracks.lilletorget.net/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "axis_camera_snapshots",
        "area": "Bilder",
        "role": "Henter og rydder Axis snapshots til soltimer",
        "runtime": "Docker",
        "compose_service": "axis_camera_snapshots",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8125/",
        "health_url": "http://192.168.20.218:8125/health",
        "health": "Filproduksjon",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "unifi_protect_events",
        "area": "Kamera",
        "role": "Lytter på lokal UniFi Protect WebSocket og lagrer filtrerte hendelser og stillbilder",
        "runtime": "Docker (profil: unifi-protect)",
        "compose_service": "unifi_protect_events",
        "interface": "Eget lokalt administrasjonsgrensesnitt og API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8130/",
        "health_url": "http://192.168.20.218:8130/health",
        "health": "/health",
        "status": "Klar for aktivering",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "visual_anomaly_service",
        "area": "Kamera",
        "role": "Lokal PatchCore-analyse av tre pullertflater og trappa ved Solstudio",
        "runtime": "Docker (profil: unifi-protect, CPU)",
        "compose_service": "visual_anomaly_service",
        "interface": "Internt tokenbeskyttet API; status vises i Fibaro10",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "/health i Docker-nettet",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": False,
    },
    {
        "component": "car_info_lookup",
        "area": "Parkering",
        "role": "Svenske og danske kjøretøyoppslag etter SVV",
        "runtime": "Docker",
        "compose_service": "car_info_lookup",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8126/",
        "health_url": "http://192.168.20.218:8126/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "sun2_session_scraper",
        "area": "Soling",
        "role": "Henter enkelttimer, senger, medlemmer og produktsalg fra Sun2",
        "runtime": "Docker",
        "compose_service": "sun2_session_scraper",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8099/",
        "health_url": "http://192.168.20.218:8099/json",
        "health": "Importjobb",
        "status": "Aktiv",
        "criticality": "Kritisk",
        "has_web_interface": True,
    },
    {
        "component": "easypark_downloader",
        "area": "Parkering",
        "role": "Nedlasting av EasyPark-data via egen app/flyt",
        "runtime": "Docker (egen compose)",
        "compose_service": "easypark_downloader",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8109/status",
        "health_url": "http://192.168.20.218:8109/health",
        "health": "easypark_parking_import",
        "status": "Aktiv/ekstern",
        "criticality": "Kritisk",
        "has_web_interface": True,
    },
    {
        "component": "parking_sun_linker",
        "area": "Kobling",
        "role": "Bakgrunnsmotor som finner sannsynlige koblinger mellom parkeringer og SUN2-brukere",
        "runtime": "Docker",
        "compose_service": "parking_sun_linker",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8127/",
        "health_url": "http://192.168.20.218:8127/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "roborock_logger",
        "area": "Renhold",
        "role": "Logger Roborock-status og vaskehistorikk",
        "runtime": "Docker (egen compose)",
        "compose_service": "roborock_logger",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8095/",
        "health_url": "http://192.168.20.218:8095/health",
        "health": "roborock_sync",
        "status": "Aktiv/ekstern",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "dreame_logger",
        "area": "Renhold",
        "role": "Logger Dreame-status, jobbhistorikk og planer for Aqua10",
        "runtime": "Docker (egen compose)",
        "compose_service": "dreame_logger",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8094/",
        "health_url": "http://192.168.20.218:8094/health",
        "health": "/health",
        "status": "Klargjort/venter på konto",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "sun2_importer",
        "area": "Soling",
        "role": "Historisk/importverktøy for Sun2 dagssummer",
        "runtime": "Docker",
        "compose_service": "sun2_importer",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8096/",
        "health_url": "http://192.168.20.218:8096/json",
        "health": "sun2_room_daily_import",
        "status": "Aktiv/verktøy",
        "criticality": "Lav",
        "has_web_interface": True,
    },
    {
        "component": "sun2_backfill_downloader",
        "area": "Soling",
        "role": "Bakfylling av historiske Sun2-filer",
        "runtime": "Docker",
        "compose_service": "sun2_backfill_downloader",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8097/",
        "health_url": "http://192.168.20.218:8097/json",
        "health": "Manuell",
        "status": "Aktiv/verktøy",
        "criticality": "Lav",
        "has_web_interface": True,
    },
    {
        "component": "browser_extensions",
        "area": "Parkering",
        "role": "Manuelle nettleserutvidelser/oppslag der API ikke dekker behov",
        "runtime": "Chrome extension",
        "compose_service": "",
        "interface": "Nettleser",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "Manuell",
        "status": "Fallback",
        "criticality": "Lav",
        "has_web_interface": False,
    },
    {
        "component": "hc3_vedlikehold",
        "area": "HC3",
        "role": "Vedlikeholds- og oppsettsskript for Fibaro HC3",
        "runtime": "Repo script",
        "compose_service": "",
        "interface": "Script/API",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "Manuell",
        "status": "Verktøy",
        "criticality": "Normal",
        "has_web_interface": False,
    },
    {
        "component": "fibaro10_proxy",
        "area": "Infrastruktur",
        "role": "Caddy reverse proxy for online, vedlikehold, alarm, iPad og OwnTracks",
        "runtime": "Docker",
        "compose_service": "fibaro10_proxy",
        "interface": "Proxy",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "docker health",
        "status": "Aktiv",
        "criticality": "Kritisk",
        "has_web_interface": False,
    },
    {
        "component": "owntracks_postgres",
        "area": "Lokasjon",
        "role": "PostgreSQL-database for OwnTracks-appen",
        "runtime": "Docker",
        "compose_service": "owntracks_postgres",
        "interface": "Database",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "docker health",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": False,
    },
]


SYSTEM_COMPONENT_TITLES: dict[str, str] = {
    "fibaro10": "Fibaro10 backend",
    "desktop_v2": "Fibaro10 reservegrensesnitt",
    "lilletorget_mantis": "Lilletorget Mantis",
    "shell_app": "Forrige Lilletorget-skall",
    "revenue_app": "Omsetning",
    "parking_app": "Parkering",
    "sun_app": "Soling",
    "energy_app": "Energi",
    "operations_app": "Bygg og drift",
    "maintenance_app": "Vedlikehold",
    "system_app": "System",
    "link_app": "Koble",
    "online_dashboard": "Mobiloversikt",
    "maintenance_mobile": "Vedlikehold mobil",
    "alarm_mobile": "Alarm mobil",
    "fibaro10ipad": "Fibaro10 iPad",
    "owntracks_service": "OwnTracks",
    "axis_camera_snapshots": "Axis bildearkiv",
    "unifi_protect_events": "UniFi Protect-hendelser",
    "visual_anomaly_service": "Visuell AI-kontroll",
    "car_info_lookup": "Nordiske kjøretøyoppslag",
    "sun2_session_scraper": "SUN2 enkelttimer og salg",
    "easypark_downloader": "EasyPark-import",
    "parking_sun_linker": "Koblingsmotor parkering og soling",
    "roborock_logger": "Roborock-logger",
    "dreame_logger": "Dreame-logger",
    "sun2_importer": "SUN2 dagsimport",
    "sun2_backfill_downloader": "SUN2 historisk bakfylling",
    "browser_extensions": "Nettleserutvidelser",
    "hc3_vedlikehold": "HC3-verktøy",
    "fibaro10_proxy": "Ekstern reverse proxy",
    "owntracks_postgres": "OwnTracks database",
}


def system_component_rows() -> list[dict[str, Any]]:
    return [dict(component) for component in SYSTEM_COMPONENTS]


def system_web_interface_rows() -> list[dict[str, Any]]:
    return [dict(component) for component in SYSTEM_COMPONENTS if component.get("has_web_interface")]


def system_subsystem_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for component in SYSTEM_COMPONENTS:
        row = dict(component)
        component_key = str(row.get("component") or "")
        links = []
        web_url = str(row.get("web_url") or "")
        local_url = str(row.get("local_url") or "")
        health_url = str(row.get("health_url") or "")
        if web_url:
            links.append({"kind": "public", "label": "Åpne", "url": web_url})
        if local_url and local_url != web_url:
            links.append({"kind": "local", "label": "Lokalt grensesnitt", "url": local_url})
        if health_url and health_url not in {web_url, local_url}:
            links.append({"kind": "health", "label": "Helsesjekk", "url": health_url})
        row.update(
            {
                "title": SYSTEM_COMPONENT_TITLES.get(component_key, component_key.replace("_", " ").title()),
                "primary_url": web_url or local_url,
                "access": "external" if web_url else "local" if local_url else "internal",
                "links": links,
            }
        )
        rows.append(row)
    return rows


def system_component_summary() -> dict[str, Any]:
    areas = Counter(str(row["area"]) for row in SYSTEM_COMPONENTS)
    statuses = Counter(str(row["status"]) for row in SYSTEM_COMPONENTS)
    active = sum(1 for row in SYSTEM_COMPONENTS if str(row["status"]).lower().startswith("aktiv"))
    critical = sum(1 for row in SYSTEM_COMPONENTS if row["criticality"] in {"Kritisk", "Høy"})
    return {
        "components": len(SYSTEM_COMPONENTS),
        "active": active,
        "critical": critical,
        "web_interfaces": len(system_web_interface_rows()),
        "areas": len(areas),
        "area_rows": [{"area": key, "count": value} for key, value in sorted(areas.items())],
        "status_rows": [{"status": key, "count": value} for key, value in sorted(statuses.items())],
    }
