"""Static system inventory for Fibaro10.

The inventory is deliberately code-owned so the admin UI, documentation and
tests can point to the same definition of which local apps are part of the
solution.
"""

from __future__ import annotations

from collections import Counter
from typing import Any


SYSTEM_COMPONENTS: list[dict[str, Any]] = [
    {
        "component": "fibaro10",
        "area": "Kjerne",
        "role": "FastAPI backend, V2 API, database, importstatus og adminflater",
        "runtime": "Docker",
        "compose_service": "fibaro10",
        "interface": "V2 web/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8110/",
        "health_url": "http://192.168.20.218:8110/health?details=true",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Kritisk",
        "has_web_interface": True,
    },
    {
        "component": "desktop_v2",
        "area": "Frontend",
        "role": "React/Ant Design grensesnitt for daglig drift",
        "runtime": "Vite build levert av fibaro10",
        "compose_service": "fibaro10",
        "interface": "Hovedgrensesnitt",
        "web_url": "",
        "local_url": "http://192.168.20.218:8110/",
        "health_url": "http://192.168.20.218:8110/health",
        "health": "/",
        "status": "Aktiv",
        "criticality": "Kritisk",
        "has_web_interface": True,
    },
    {
        "component": "online_dashboard",
        "area": "Mobil/ekstern",
        "role": "Eksternt dashboard med begrensede nøkkeltall",
        "runtime": "Docker",
        "compose_service": "online_dashboard",
        "interface": "Offentlig web",
        "web_url": "https://online.lilletorget.net/",
        "local_url": "http://192.168.20.218:8111/",
        "health_url": "https://online.lilletorget.net/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "maintenance_mobile",
        "area": "Vedlikehold",
        "role": "Mobilapp for rask registrering av vedlikehold og oppgaver",
        "runtime": "Docker",
        "compose_service": "maintenance_mobile",
        "interface": "Offentlig web",
        "web_url": "https://vedl.lilletorget.net/",
        "local_url": "http://192.168.20.218:8112/",
        "health_url": "https://vedl.lilletorget.net/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "fibaro10ipad",
        "area": "Frontend",
        "role": "Separat iPad-grensesnitt for sentrale driftsbilder fra Fibaro10",
        "runtime": "Docker",
        "compose_service": "fibaro10ipad",
        "interface": "Offentlig web",
        "web_url": "https://ipad.lilletorget.net/",
        "local_url": "http://192.168.20.218:8113/",
        "health_url": "https://ipad.lilletorget.net/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "owntracks_service",
        "area": "Lokasjon",
        "role": "Separat FastAPI-tjeneste på owntracks.lilletorget.net for OwnTracks HTTP-inntak, lagring, waypoints og sonebesøk",
        "runtime": "Docker",
        "compose_service": "owntracks_service",
        "interface": "Offentlig web/API",
        "web_url": "https://owntracks.lilletorget.net/",
        "local_url": "http://192.168.20.218:8128/",
        "health_url": "https://owntracks.lilletorget.net/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "axis_camera_snapshots",
        "area": "Bilder",
        "role": "Henter og rydder Axis snapshots til soltimer",
        "runtime": "Docker",
        "compose_service": "axis_camera_snapshots",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8125/",
        "health_url": "http://192.168.20.218:8125/health",
        "health": "Filproduksjon",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "car_info_lookup",
        "area": "Parkering",
        "role": "Svenske og danske kjøretøyoppslag etter SVV",
        "runtime": "Docker",
        "compose_service": "car_info_lookup",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8126/",
        "health_url": "http://192.168.20.218:8126/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Normal",
        "has_web_interface": True,
    },
    {
        "component": "sun2_session_scraper",
        "area": "Soling",
        "role": "Henter enkelttimer, senger, medlemmer og produktsalg fra Sun2",
        "runtime": "Docker",
        "compose_service": "sun2_session_scraper",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8099/",
        "health_url": "http://192.168.20.218:8099/json",
        "health": "Importjobb",
        "status": "Aktiv",
        "criticality": "Kritisk",
        "has_web_interface": True,
    },
    {
        "component": "easypark_downloader",
        "area": "Parkering",
        "role": "Nedlasting av EasyPark-data via egen app/flyt",
        "runtime": "Repo app",
        "compose_service": "easypark_downloader",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8109/status",
        "health_url": "http://192.168.20.218:8109/health",
        "health": "easypark_parking_import",
        "status": "Aktiv/ekstern",
        "criticality": "Kritisk",
        "has_web_interface": True,
    },
    {
        "component": "parking_sun_linker",
        "area": "Kobling",
        "role": "Bakgrunnsmotor som finner sannsynlige koblinger mellom parkeringer og SUN2-brukere",
        "runtime": "Docker",
        "compose_service": "parking_sun_linker",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8127/",
        "health_url": "http://192.168.20.218:8127/health",
        "health": "/health",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": True,
    },
    {
        "component": "roborock_logger",
        "area": "Renhold",
        "role": "Logger Roborock-status og vaskehistorikk",
        "runtime": "Repo app",
        "compose_service": "",
        "interface": "Bakgrunnsjobb",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "roborock_sync",
        "status": "Aktiv/ekstern",
        "criticality": "Normal",
        "has_web_interface": False,
    },
    {
        "component": "sun2_importer",
        "area": "Soling",
        "role": "Historisk/importverktøy for Sun2 dagssummer",
        "runtime": "Repo app",
        "compose_service": "",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8096/",
        "health_url": "http://192.168.20.218:8096/json",
        "health": "sun2_room_daily_import",
        "status": "Verktøy",
        "criticality": "Lav",
        "has_web_interface": True,
    },
    {
        "component": "sun2_backfill_downloader",
        "area": "Soling",
        "role": "Bakfylling av historiske Sun2-filer",
        "runtime": "Repo app",
        "compose_service": "",
        "interface": "Lokal status/API",
        "web_url": "",
        "local_url": "http://192.168.20.218:8097/",
        "health_url": "http://192.168.20.218:8097/json",
        "health": "Manuell",
        "status": "Verktøy",
        "criticality": "Lav",
        "has_web_interface": True,
    },
    {
        "component": "browser_extensions",
        "area": "Parkering",
        "role": "Manuelle nettleserutvidelser/oppslag der API ikke dekker behov",
        "runtime": "Chrome extension",
        "compose_service": "",
        "interface": "Nettleser",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "Manuell",
        "status": "Fallback",
        "criticality": "Lav",
        "has_web_interface": False,
    },
    {
        "component": "hc3_vedlikehold",
        "area": "HC3",
        "role": "Vedlikeholds- og oppsettsskript for Fibaro HC3",
        "runtime": "Repo script",
        "compose_service": "",
        "interface": "Script/API",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "Manuell",
        "status": "Verktøy",
        "criticality": "Normal",
        "has_web_interface": False,
    },
    {
        "component": "fibaro10_proxy",
        "area": "Infrastruktur",
        "role": "Caddy reverse proxy for online, vedlikehold og OwnTracks",
        "runtime": "Docker",
        "compose_service": "fibaro10_proxy",
        "interface": "Proxy",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "docker health",
        "status": "Aktiv",
        "criticality": "Kritisk",
        "has_web_interface": False,
    },
    {
        "component": "owntracks_postgres",
        "area": "Lokasjon",
        "role": "PostgreSQL-database for OwnTracks-appen",
        "runtime": "Docker",
        "compose_service": "owntracks_postgres",
        "interface": "Database",
        "web_url": "",
        "local_url": "",
        "health_url": "",
        "health": "docker health",
        "status": "Aktiv",
        "criticality": "Høy",
        "has_web_interface": False,
    },
]


def system_component_rows() -> list[dict[str, Any]]:
    return [dict(component) for component in SYSTEM_COMPONENTS]


def system_web_interface_rows() -> list[dict[str, Any]]:
    return [dict(component) for component in SYSTEM_COMPONENTS if component.get("has_web_interface")]


def system_component_summary() -> dict[str, Any]:
    areas = Counter(str(row["area"]) for row in SYSTEM_COMPONENTS)
    statuses = Counter(str(row["status"]) for row in SYSTEM_COMPONENTS)
    active = sum(1 for row in SYSTEM_COMPONENTS if str(row["status"]).lower().startswith("aktiv"))
    critical = sum(1 for row in SYSTEM_COMPONENTS if row["criticality"] in {"Kritisk", "Høy"})
    return {
        "components": len(SYSTEM_COMPONENTS),
        "active": active,
        "critical": critical,
        "web_interfaces": len(system_web_interface_rows()),
        "areas": len(areas),
        "area_rows": [{"area": key, "count": value} for key, value in sorted(areas.items())],
        "status_rows": [{"status": key, "count": value} for key, value in sorted(statuses.items())],
    }
