persistence true
persistence_location /mosquitto/data/
autosave_interval 60

log_dest stdout
log_timestamp true
connection_messages true

allow_anonymous false
password_file /mosquitto/data/passwords
acl_file /mosquitto/data/acl

listener 1883 0.0.0.0
