export const smokeRoutes = [
  { path: "/status/omsetning", name: "Dashboard omsetning" },
  { path: "/status/parkering", name: "Dashboard parkering" },
  { path: "/status/soling", name: "Dashboard soling" },
  { path: "/status/drift", name: "Dashboard drift" },
  { path: "/omsetning/oversikt", name: "Omsetning oversikt" },
  { path: "/omsetning/manedsoversikt", name: "Omsetning manedsoversikt" },
  { path: "/omsetning/akkumulert", name: "Omsetning arssammenligning" },
  { path: "/omsetning/sammenligning", name: "Omsetning periodesammenligning" },
  { path: "/parkering/oversikt", name: "Parkering oversikt" },
  { path: "/parkering/sammenligning", name: "Parkering arssammenligning" },
  { path: "/parkering/dagslinje", name: "Parkering dagslinje" },
  { path: "/parkering/tidspunkt", name: "Parkering tidspunkt" },
  { path: "/parkering/parkeringer", name: "Parkeringer" },
  { path: "/parkering/kjoretoy", name: "Kjoretoy" },
  { path: "/parkering/prognose", name: "Parkering prognose" },
  { path: "/parkering/omrade", name: "Parkering omrade" },
  { path: "/parkering/bilstatistikk", name: "Bilstatistikk" },
  { path: "/parkering/oppgjor", name: "Parkering oppgjor" },
  { path: "/parkering/oppslag", name: "Parkering oppslag" },
  { path: "/soling/oversikt", name: "Soling oversikt" },
  { path: "/soling/sammenligning", name: "Soling arssammenligning" },
  { path: "/soling/dagslinje", name: "Soling dagslinje" },
  { path: "/soling/enkeltimer", name: "Soling enkelttimer" },
  { path: "/soling/senger", name: "Soling senger" },
  { path: "/soling/medlemmer", name: "Soling medlemmer" },
  { path: "/soling/produkter", name: "Soling produkter" },
  { path: "/soling/prognose", name: "Soling prognose" },
  { path: "/soling/oppgjor", name: "Soling oppgjor" },
  { path: "/soling/statistikk", name: "Soling statistikk" },
  { path: "/soling/detaljer", name: "Soling detaljer" },
  { path: "/koble/oversikt", name: "Koble oversikt" },
  { path: "/koble/sun2", name: "Koble SUN2-kontroll" },
  { path: "/koble/biltreff", name: "Koble biltreff" },
  { path: "/koble/kandidater", name: "Koble kandidater" },
  { path: "/koble/treffgrunnlag", name: "Koble treffgrunnlag" },
  { path: "/koble/jobb", name: "Koble jobb" },
  { path: "/energi/status", name: "Energi status" },
  { path: "/energi/kurser", name: "Energi kurser" },
  { path: "/energi/laster", name: "Energi laster" },
  { path: "/energi/forbruk-per-seng", name: "Energi forbruk per seng" },
  { path: "/energi/elvia", name: "Energi Elvia" },
  { path: "/energi/elvia-kontroll", name: "Energi Elvia-kontroll" },
  { path: "/energi/verktoy", name: "Energi verktoy" },
  { path: "/ventilasjon/dagslogg", name: "Ventilasjon dagslogg" },
  { path: "/ventilasjon/temp-logg", name: "Ventilasjon temperatur og fukt" },
  { path: "/ventilasjon/yr-logg", name: "Ventilasjon Yr-logg" },
  { path: "/ventilasjon/hendelser", name: "Ventilasjon hendelser" },
  { path: "/ventilasjon/innstillinger", name: "Ventilasjon innstillinger" },
  { path: "/lys/dagslogg", name: "Lys dagslogg" },
  { path: "/lys/lux-logging", name: "Lux-logg" },
  { path: "/lys/hendelser", name: "Lys hendelser" },
  { path: "/lys/innstillinger", name: "Lys innstillinger" },
  { path: "/dorer/oversikt", name: "Dorer oversikt" },
  { path: "/dorer/oversikt-ny", name: "Dorer oversikt ny" },
  { path: "/dorer/soltimer", name: "Dorer dor og soltime" },
  { path: "/dorer/romkontroll", name: "Dorer romkontroll", expectedTexts: ["Romkontroll", "Rom 1", "Forventet ut", "Strøm OK"] },
  { path: "/dorer/romkontroll-ny", name: "Dorer romkontroll ny", expectedTexts: ["Romkontroll - ny", "Rom 1"] },
  { path: "/dorer/romkontroll-ny2", name: "Dorer romkontroll ny2", expectedTexts: ["Romkontroll - ny2", "Dato", "Dør lukket", "Hendelse"] },
  { path: "/dorer/solrom", name: "Dorer solrom" },
  { path: "/dorer/solrom-ny", name: "Dorer solrom ny", expectedTexts: ["Solrom - ny", "Dato", "Hendelse"] },
  { path: "/dorer/andre", name: "Dorer andre" },
  { path: "/dorer/radata", name: "Dorer radata" },
  { path: "/vedlikehold/oversikt", name: "Vedlikehold oversikt" },
  { path: "/vedlikehold/besok", name: "Vedlikehold besok" },
  { path: "/ideer/oversikt", name: "Ideer oversikt" },
  { path: "/ideer/kontroll", name: "Ideer kontroll" },
  { path: "/ideer/innsikt", name: "Ideer innsikt" },
  { path: "/ideer/automatisering", name: "Ideer automatisering" },
  { path: "/ideer/arbeidsflyt", name: "Ideer arbeidsflyt" },
  { path: "/renhold/oversikt", name: "Renhold oversikt" },
  { path: "/renhold/roboter", name: "Renhold roboter" },
  { path: "/mobil/oversikt", name: "Mobil oversikt" },
  { path: "/manual/oversikt", name: "Manual oversikt", expectedTexts: ["Lilletorget drift", "Undersider"] },
  { path: "/manual/daglig-bruk", name: "Manual daglig bruk", expectedTexts: ["Daglig bruk"] },
  { path: "/manual/menyvalg", name: "Manual menyvalg", expectedTexts: ["Menyvalg"] },
  { path: "/manual/okonomi", name: "Manual okonomi", expectedTexts: ["Økonomi"] },
  { path: "/manual/bygg-drift", name: "Manual bygg og drift", expectedTexts: ["Bygg og drift"] },
  { path: "/manual/system", name: "Manual system", expectedTexts: ["System"] },
  { path: "/manual/datagrunnlag", name: "Manual datagrunnlag", expectedTexts: ["Datagrunnlag"] },
  { path: "/manual/rutiner", name: "Manual rutiner", expectedTexts: ["Rutiner"] },
  { path: "/manual/feilsoking", name: "Manual feilsoking", expectedTexts: ["Feilsøking"] },
  { path: "/admin/oppgaver", name: "Admin oppgaver" },
  { path: "/admin/kontroll", name: "Admin kontroll" },
  { path: "/admin/datakvalitet", name: "Admin datakvalitet" },
  { path: "/admin/analyse", name: "Admin analyse" },
  { path: "/admin/drift", name: "Admin drift" },
  { path: "/admin/build", name: "Admin buildlogg" },
  { path: "/admin/datakilder", name: "Admin datakilder" },
  { path: "/admin/datakilder/easypark_parking_import", name: "Admin datakilde detalj" },
  { path: "/admin/systemkart", name: "Admin systemkart" },
  { path: "/admin/ai", name: "Admin AI" },
  { path: "/admin/teknisk", name: "Admin teknisk" },
  { path: "/admin/brukere", name: "Admin brukere" },
  { path: "/admin/verktoy", name: "Admin verktoy" },
];

export function smokeRoutePathsFromEnv(value) {
  const explicit = String(value || "")
    .split(",")
    .map((route) => route.trim())
    .filter(Boolean);
  return explicit.length ? explicit.map((path) => ({ path, name: path })) : smokeRoutes;
}
