services:
  easypark_downloader:
    build: .
    container_name: easypark_downloader
    restart: unless-stopped
    env_file: .env
    ports:
      - "8109:8109"
    volumes:
      - ./data:/data
    networks:
      - default
      - fibaro10

networks:
  fibaro10:
    external: true
    name: fibaro10_default
