import { MosaicIcon, Panel } from "@lilletorget/microapp-ui";
import { AppLink } from "@lilletorget/microapp-ui/router";
import type { RoborockRobotSummary } from "../../roborock-types";

export function DreameOnboarding({ robot }: { robot?: RoborockRobotSummary }) {
  return <div className="space-y-5">
    <AppLink className="inline-flex items-center gap-2 text-sm font-medium text-gray-500 hover:text-amber-700 dark:text-gray-400 dark:hover:text-amber-300" to="/renhold"><MosaicIcon name="arrow-left" size={14} />Alle robotvaskere</AppLink>
    <section className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-700/60 dark:bg-gray-800">
      <header className="flex flex-wrap items-center justify-between gap-4 border-b border-gray-100 px-5 py-4 dark:border-gray-700/60"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-amber-500/10 text-amber-600 dark:text-amber-300"><MosaicIcon name="robot" size={22} /></span><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-gray-800 dark:text-gray-100">{robot?.name || "Aqua10"}</h2><span className="rounded bg-gray-100 px-1.5 py-0.5 text-[0.65rem] font-semibold uppercase text-gray-500 dark:bg-gray-700 dark:text-gray-300">Dreame</span></div><p className="text-sm text-gray-400">Separat datainnsamling, felles renholdsoversikt</p></div></div><span className="inline-flex items-center gap-2 rounded-full bg-amber-500/10 px-3 py-1.5 text-xs font-semibold text-amber-700 dark:text-amber-300"><span className="h-2 w-2 rounded-full bg-amber-500" />Venter på konto</span></header>
      <div className="grid gap-0 lg:grid-cols-[minmax(0,1.25fr)_minmax(20rem,0.75fr)]">
        <div className="px-5 py-5 lg:border-r lg:border-gray-100 dark:lg:border-gray-700/60"><h3 className="text-sm font-semibold text-gray-800 dark:text-gray-100">Klargjort oppsett</h3><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["01", "Dreamehome", "Legg roboten til og gi den navnet Aqua10."], ["02", "Sikker kobling", "Legg kontoen i dreame_logger/.env på QNAP."], ["03", "Automatisk opprettelse", "Status, jobber og planer dukker opp ved første synk."]].map(([number, title, text]) => <div className="rounded-md bg-gray-50 p-3 dark:bg-gray-900/30" key={number}><span className="text-xs font-semibold tabular-nums text-amber-600 dark:text-amber-300">{number}</span><strong className="mt-1 block text-sm text-gray-700 dark:text-gray-200">{title}</strong><p className="mt-1 text-xs leading-5 text-gray-400">{text}</p></div>)}</div></div>
        <div className="bg-gray-50/60 px-5 py-5 dark:bg-gray-900/20"><h3 className="text-sm font-semibold text-gray-800 dark:text-gray-100">Dreame-logger</h3><p className="mt-2 text-sm leading-6 text-gray-500 dark:text-gray-400">Tjenesten kjører separat fra Roborock. En feil eller oppgradering hos én leverandør stopper derfor ikke den andre.</p><a className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-amber-700 hover:text-amber-800 dark:text-amber-300" href="http://192.168.20.218:8094/" rel="noreferrer" target="_blank">Åpne intern tjenestestatus <MosaicIcon name="arrow-right" size={14} /></a></div>
      </div>
    </section>
    <Panel title="Datadekning" subtitle="Første versjon prioriterer stabil drift fremfor kartbehandling"><div className="grid gap-px bg-gray-100 sm:grid-cols-2 lg:grid-cols-4 dark:bg-gray-700/60">{[["Tilstand", "Batteri, lading, feil og aktiv jobb"], ["Jobbhistorikk", "Start, slutt, varighet og rengjort areal"], ["Dokk og beholdere", "Tilgjengelige signaler for vann, vask og tømming"], ["Planer", "Aktive tidsplaner og gjennomføring"]].map(([title, text]) => <div className="bg-white px-5 py-4 dark:bg-gray-800" key={title}><strong className="text-sm text-gray-700 dark:text-gray-200">{title}</strong><p className="mt-1 text-xs leading-5 text-gray-400">{text}</p></div>)}</div></Panel>
  </div>;
}
